# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('hula', ['point-to-point'])
    module.source = [
        'model/hula_hdr.cc',
        'model/flowlet.cc',
        'model/rpc-application.cc',
        'model/hulaProbeGenerator.cc',
        'model/hula-routing.cc',
        'helper/hula-generator-helper.cc',
        'helper/hula-routing-helper.cc',
        'helper/rpc-generator-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('hula')
    module_test.source = [
        'test/hula-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'hula'
    headers.source = [
        'model/hula_hdr.h',
        'model/flowlet.h',
        'model/rpc-application.h',
        'model/hulaProbeGenerator.h',
        'model/hula-routing.h',
        'helper/hula-generator-helper.h',
        'helper/hula-routing-helper.h',
        'helper/rpc-generator-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

